# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='author',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='isbn',
            field=isbn_field.fields.ISBNField(default=True, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='publication',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='title',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
